/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdministrativeRouteImport } from './routes/administrative'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as AdministrativeIndexRouteImport } from './routes/administrative.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdministrativeUsersRouteImport } from './routes/administrative.users'
import { Route as AdministrativeTenantsRouteImport } from './routes/administrative.tenants'
import { Route as AdministrativeSettingsRouteImport } from './routes/administrative.settings'
import { Route as AdministrativeHomeRouteImport } from './routes/administrative.home'
import { Route as AdministrativeAnalyticsRouteImport } from './routes/administrative.analytics'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminMembersAreaRouteImport } from './routes/admin/members-area'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminGroupsRouteImport } from './routes/admin/groups'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin/enrollments'

const AdministrativeRoute = AdministrativeRouteImport.update({
  id: '/administrative',
  path: '/administrative',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativeIndexRoute = AdministrativeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdministrativeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdministrativeUsersRoute = AdministrativeUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdministrativeRoute,
} as any)
const AdministrativeTenantsRoute = AdministrativeTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdministrativeRoute,
} as any)
const AdministrativeSettingsRoute = AdministrativeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdministrativeRoute,
} as any)
const AdministrativeHomeRoute = AdministrativeHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdministrativeRoute,
} as any)
const AdministrativeAnalyticsRoute = AdministrativeAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdministrativeRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersAreaRoute = AdminMembersAreaRouteImport.update({
  id: '/members-area',
  path: '/members-area',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/administrative': typeof AdministrativeRouteWithChildren
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/members-area': typeof AdminMembersAreaRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/administrative/analytics': typeof AdministrativeAnalyticsRoute
  '/administrative/home': typeof AdministrativeHomeRoute
  '/administrative/settings': typeof AdministrativeSettingsRoute
  '/administrative/tenants': typeof AdministrativeTenantsRoute
  '/administrative/users': typeof AdministrativeUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/administrative/': typeof AdministrativeIndexRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/members-area': typeof AdminMembersAreaRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/administrative/analytics': typeof AdministrativeAnalyticsRoute
  '/administrative/home': typeof AdministrativeHomeRoute
  '/administrative/settings': typeof AdministrativeSettingsRoute
  '/administrative/tenants': typeof AdministrativeTenantsRoute
  '/administrative/users': typeof AdministrativeUsersRoute
  '/admin': typeof AdminIndexRoute
  '/administrative': typeof AdministrativeIndexRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/administrative': typeof AdministrativeRouteWithChildren
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/members-area': typeof AdminMembersAreaRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/administrative/analytics': typeof AdministrativeAnalyticsRoute
  '/administrative/home': typeof AdministrativeHomeRoute
  '/administrative/settings': typeof AdministrativeSettingsRoute
  '/administrative/tenants': typeof AdministrativeTenantsRoute
  '/administrative/users': typeof AdministrativeUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/administrative/': typeof AdministrativeIndexRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/administrative'
    | '/admin/enrollments'
    | '/admin/groups'
    | '/admin/members'
    | '/admin/members-area'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/administrative/analytics'
    | '/administrative/home'
    | '/administrative/settings'
    | '/administrative/tenants'
    | '/administrative/users'
    | '/admin/'
    | '/administrative/'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/enrollments'
    | '/admin/groups'
    | '/admin/members'
    | '/admin/members-area'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/administrative/analytics'
    | '/administrative/home'
    | '/administrative/settings'
    | '/administrative/tenants'
    | '/administrative/users'
    | '/admin'
    | '/administrative'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/administrative'
    | '/admin/enrollments'
    | '/admin/groups'
    | '/admin/members'
    | '/admin/members-area'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/administrative/analytics'
    | '/administrative/home'
    | '/administrative/settings'
    | '/administrative/tenants'
    | '/administrative/users'
    | '/admin/'
    | '/administrative/'
    | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdministrativeRoute: typeof AdministrativeRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/administrative': {
      id: '/administrative'
      path: '/administrative'
      fullPath: '/administrative'
      preLoaderRoute: typeof AdministrativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrative/': {
      id: '/administrative/'
      path: '/'
      fullPath: '/administrative/'
      preLoaderRoute: typeof AdministrativeIndexRouteImport
      parentRoute: typeof AdministrativeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/administrative/users': {
      id: '/administrative/users'
      path: '/users'
      fullPath: '/administrative/users'
      preLoaderRoute: typeof AdministrativeUsersRouteImport
      parentRoute: typeof AdministrativeRoute
    }
    '/administrative/tenants': {
      id: '/administrative/tenants'
      path: '/tenants'
      fullPath: '/administrative/tenants'
      preLoaderRoute: typeof AdministrativeTenantsRouteImport
      parentRoute: typeof AdministrativeRoute
    }
    '/administrative/settings': {
      id: '/administrative/settings'
      path: '/settings'
      fullPath: '/administrative/settings'
      preLoaderRoute: typeof AdministrativeSettingsRouteImport
      parentRoute: typeof AdministrativeRoute
    }
    '/administrative/home': {
      id: '/administrative/home'
      path: '/home'
      fullPath: '/administrative/home'
      preLoaderRoute: typeof AdministrativeHomeRouteImport
      parentRoute: typeof AdministrativeRoute
    }
    '/administrative/analytics': {
      id: '/administrative/analytics'
      path: '/analytics'
      fullPath: '/administrative/analytics'
      preLoaderRoute: typeof AdministrativeAnalyticsRouteImport
      parentRoute: typeof AdministrativeRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members-area': {
      id: '/admin/members-area'
      path: '/members-area'
      fullPath: '/admin/members-area'
      preLoaderRoute: typeof AdminMembersAreaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminMembersAreaRoute: typeof AdminMembersAreaRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminMembersAreaRoute: AdminMembersAreaRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AdministrativeRouteChildren {
  AdministrativeAnalyticsRoute: typeof AdministrativeAnalyticsRoute
  AdministrativeHomeRoute: typeof AdministrativeHomeRoute
  AdministrativeSettingsRoute: typeof AdministrativeSettingsRoute
  AdministrativeTenantsRoute: typeof AdministrativeTenantsRoute
  AdministrativeUsersRoute: typeof AdministrativeUsersRoute
  AdministrativeIndexRoute: typeof AdministrativeIndexRoute
}

const AdministrativeRouteChildren: AdministrativeRouteChildren = {
  AdministrativeAnalyticsRoute: AdministrativeAnalyticsRoute,
  AdministrativeHomeRoute: AdministrativeHomeRoute,
  AdministrativeSettingsRoute: AdministrativeSettingsRoute,
  AdministrativeTenantsRoute: AdministrativeTenantsRoute,
  AdministrativeUsersRoute: AdministrativeUsersRoute,
  AdministrativeIndexRoute: AdministrativeIndexRoute,
}

const AdministrativeRouteWithChildren = AdministrativeRoute._addFileChildren(
  AdministrativeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdministrativeRoute: AdministrativeRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
