/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdministrativePanelRouteImport } from './routes/administrative-panel'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as AdministrativePanelIndexRouteImport } from './routes/administrative-panel.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdministrativePanelHomeRouteImport } from './routes/administrative-panel.home'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminGroupsRouteImport } from './routes/admin/groups'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin/enrollments'

const AdministrativePanelRoute = AdministrativePanelRouteImport.update({
  id: '/administrative-panel',
  path: '/administrative-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativePanelIndexRoute =
  AdministrativePanelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdministrativePanelRoute,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdministrativePanelHomeRoute = AdministrativePanelHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdministrativePanelRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/administrative-panel': typeof AdministrativePanelRouteWithChildren
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/administrative-panel/home': typeof AdministrativePanelHomeRoute
  '/admin/': typeof AdminIndexRoute
  '/administrative-panel/': typeof AdministrativePanelIndexRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/administrative-panel/home': typeof AdministrativePanelHomeRoute
  '/admin': typeof AdminIndexRoute
  '/administrative-panel': typeof AdministrativePanelIndexRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/administrative-panel': typeof AdministrativePanelRouteWithChildren
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/administrative-panel/home': typeof AdministrativePanelHomeRoute
  '/admin/': typeof AdminIndexRoute
  '/administrative-panel/': typeof AdministrativePanelIndexRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/administrative-panel'
    | '/admin/enrollments'
    | '/admin/groups'
    | '/admin/members'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/administrative-panel/home'
    | '/admin/'
    | '/administrative-panel/'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/enrollments'
    | '/admin/groups'
    | '/admin/members'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/administrative-panel/home'
    | '/admin'
    | '/administrative-panel'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/administrative-panel'
    | '/admin/enrollments'
    | '/admin/groups'
    | '/admin/members'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/administrative-panel/home'
    | '/admin/'
    | '/administrative-panel/'
    | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdministrativePanelRoute: typeof AdministrativePanelRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/administrative-panel': {
      id: '/administrative-panel'
      path: '/administrative-panel'
      fullPath: '/administrative-panel'
      preLoaderRoute: typeof AdministrativePanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrative-panel/': {
      id: '/administrative-panel/'
      path: '/'
      fullPath: '/administrative-panel/'
      preLoaderRoute: typeof AdministrativePanelIndexRouteImport
      parentRoute: typeof AdministrativePanelRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/administrative-panel/home': {
      id: '/administrative-panel/home'
      path: '/home'
      fullPath: '/administrative-panel/home'
      preLoaderRoute: typeof AdministrativePanelHomeRouteImport
      parentRoute: typeof AdministrativePanelRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AdministrativePanelRouteChildren {
  AdministrativePanelHomeRoute: typeof AdministrativePanelHomeRoute
  AdministrativePanelIndexRoute: typeof AdministrativePanelIndexRoute
}

const AdministrativePanelRouteChildren: AdministrativePanelRouteChildren = {
  AdministrativePanelHomeRoute: AdministrativePanelHomeRoute,
  AdministrativePanelIndexRoute: AdministrativePanelIndexRoute,
}

const AdministrativePanelRouteWithChildren =
  AdministrativePanelRoute._addFileChildren(AdministrativePanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdministrativePanelRoute: AdministrativePanelRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
